name: Machine Learning Workflow CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Workflow-CI/**'

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install pandas scikit-learn mlflow matplotlib seaborn

    - name: Run MLflow Project (Re-training Model)
      run: |
        cd Workflow-CI/MLProject
        mlflow run . --env-manager local

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push MLflow Docker Image
      run: |
        cd Workflow-CI/MLProject
        # Mencari folder model yang baru saja diexport di mlruns lokal secara otomatis
        MODEL_PATH=$(find mlruns/ -type d -name "model" | head -n 1)
        echo "Menggunakan model lokal dari jalur: $MODEL_PATH"
        
        # Membangun docker image langsung dari model lokal tanpa bergantung dengan ID Run DagsHub
        mlflow models build-docker -m "$MODEL_PATH" -n "${{ secrets.DOCKER_HUB_USERNAME }}/heart-disease-model:latest"
        
        # Mengunggah hasil build docker ke repositori Docker Hub Pitria
        docker push "${{ secrets.DOCKER_HUB_USERNAME }}/heart-disease-model:latest"